### ISSUE TITLE
EQL: count func with a conditional?

### ISSUE THREAD

**Issue by jimyx17** [krotik/eliasdb#15]
Hi Krotik

Don't really know if this is supported right now, but I'd rally need to add a condition to the @count function in a conditional statement. For instance, with the dataset provided in the tutorial, let's try to get the stations that are in 2 or more lines whose names begin with D.

I was thinking in something like:

`get Station where @count(:Connection::Line where Name beginswith D) > 1`

Is there any possibility for this to be added to the EQL language?

Tahnks!

**Comment by krotik** [comment]
That's an interesting idea - let me think about it ...

**Comment by krotik** [comment]
Hey there,

I've implemented now the extension to the @count function. Since it is a function I have to put the condition as a string which is parsed during runtime. You can now write the following query on the tutorial data:

`get Station where @count(:StationOnLine::Line, 'name beginswith C') > 1 show name`

This should give the following result:

>Name
>1:n:name
>--
>Liverpool Street
>Notting Hill Gate

(The two stations where Central Line and Circle Line cross)

Let me know if this solves your problem...

**Comment by jimyx17** [comment]
That actually works for me!!

Thanks!!!

**Comment by krotik** [comment]
Cool - I'll close this issue. Please reopen or create a new one if you have more suggestions.
