### ISSUE TITLE
Eliasdb status

### ISSUE THREAD

**Issue by ansarizafar** [krotik/eliasdb#32]
Is eliasdb production reading? What are  the future plans for this project? will it be maintained?

**Comment by krotik** [comment]
Production ready is a fairly subjective term - I have no idea how often nor how successful EliasDB was used in a "production environment". However, it is around since 2016, has a good coverage with unit tests and not a lot of bugs were raised. The main code paths (i.e. DB storage and API) are stable and I don't plan to do significant changes there any time soon. Semantic versioning is used in the release process - we're now at version 1.2 after 5 years.

As for the future plans: You can see in the issues section a few feature requests which I'll consider for the next features. Other than that I don't have concrete plans yet. I do plan to continue to maintain it. However, so far the project is a 1 person project with limited time resources and relative high expectations in terms of quality - development on this is bound to be slow moving.
